version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: geminiteste
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    depends_on:
      - postgres
    environment:
      PG_HOST: postgres
      DB_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: root
      PG_DB: geminiteste
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "3000:3000"


volumes:
  postgres_data:
